---
name: Schedule - Sync secrets

on:
  workflow_dispatch:
  schedule:
    - cron: "15 * * * *"
  push:
    branches:
      - main
    paths:
      - .github/workflows/schedule-sync-secrets.yaml

jobs:
  sync_secrets_and_vars:
    environment: production
    name: Sync secrets and variables
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - kireque/home-ops
    steps:
      - name: Sync Secrets and Variables
        uses: cbrgm/sync-secrets-action@v1
        with:
          github-token: ${{ secrets.SECRET_SYNC_TOKEN }}
          target: ${{ matrix.repo }}
          type: actions
          secrets: |
            KIREQUE_APP_ID=${{ secrets.KIREQUE_APP_ID }}
            KIREQUE_APP_PRIVATE_KEY="${{ secrets.KIREQUE_APP_PRIVATE_KEY }}"