---
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: false
        required: false
        type: boolean
      autodiscover_filter:
        description: "Autodiscover filter"
        default: "*"
        required: false
      cache:
        description: Use Renovate cache from GitHub repo's cache?
        type: choice
        default: "enabled"
        options:
          - enabled
          - disabled
          - reset
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    - cron: "0 * * * *"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.KIREQUE_APP_ID }}
          private-key: ${{ secrets.KIREQUE_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Renovate Cache
        id: renovate-cache
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        if: github.event.inputs.cache != 'disabled'
        continue-on-error: true
        with:
          path: /tmp/renovate/cache/renovate/repository
          key: renovate-cache-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            renovate-cache-${{ runner.os }}

      - name: Set cache folder permissions
        shell: bash
        run: |
          # chown /tmp/renovate due to cache permissions
          # UID from https://github.com/renovatebot/renovate/blob/9c999fb13e8746830a0c163bad9c244b0b926c6a/tools/docker/Dockerfile#L114
          mkdir -p /tmp/renovate
          sudo chown -R 12021:$(id -g) /tmp/renovate

      - name: Renovate
        uses: renovatebot/github-action@6927a58a017ee9ac468a34a5b0d2a9a9bd45cac3 # v43.0.11
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'debug' }}
          RENOVATE_ALLOWED_COMMANDS: '["npm run bundle"]'
          RENOVATE_DRY_RUN: ${{ inputs.dryRun == true }}
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: ${{ github.repository_owner }}/${{ inputs.autodiscover_filter || '*' }}
          RENOVATE_PLATFORM: github
          RENOVATE_PLATFORM_COMMIT: true
          RENOVATE_REPOSITORY_CACHE: ${{ github.event.inputs.cache }}
        with:
          token: "${{ steps.app-token.outputs.token }}"
